# syntax=docker/dockerfile:1

FROM node:22-alpine

WORKDIR /workspace
ENV NODE_ENV=development

COPY . .
RUN yarn install --frozen-lockfile --ignore-optional

ARG SERVICE_PATH
ENV SERVICE_PATH=${SERVICE_PATH}

CMD ["sh", "-c", "cd \"$SERVICE_PATH\" && yarn -s tsx src/main.ts"]
