import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type CreateAppointmentRequest = OperationRequest<'createAppointment'>;
export type CreateAppointmentResponse = OperationResponseByStatus<'createAppointment', 201>;

export type ListCompanyAppointmentsResponse = OperationResponseByStatus<'listCompanyAppointments', 200>;

export type RespondToAppointmentRequest = OperationRequest<'respondToAppointment'>;
export type RespondToAppointmentResponse = OperationResponseByStatus<'respondToAppointment', 200>;

export type ListMyAppointmentsResponse = OperationResponseByStatus<'listMyAppointments', 200>;
export type CancelAppointmentResponse = OperationResponseByStatus<'cancelAppointment', 200>;
export type CompleteAppointmentResponse = OperationResponseByStatus<'completeAppointment', 200>;

export type AppointmentSchema = Schema<'Appointment'>;
