import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type CreateSpecialistProfileRequest = OperationRequest<'createSpecialistProfile'>;
export type CreateSpecialistProfileResponse = OperationResponseByStatus<'createSpecialistProfile', 201>;

export type GetMySpecialistProfileResponse = OperationResponseByStatus<'getMySpecialistProfile', 200>;

export type UpdateSpecialistProfileRequest = OperationRequest<'updateMySpecialistProfile'>;
export type UpdateMySpecialistProfileResponse = OperationResponseByStatus<'updateMySpecialistProfile', 200>;

export type GetPublicSpecialistsResponse = OperationResponseByStatus<'getPublicSpecialists', 200>;

export type GetSpecialistByIdResponse = OperationResponseByStatus<'getSpecialistById', 200>;

export type SpecialistProfileSchema = Schema<'SpecialistProfile'>;
