import type { OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type ListMyNotificationsResponse = OperationResponseByStatus<'listMyNotifications', 200>;
export type GetUnreadNotificationCountResponse = OperationResponseByStatus<'getUnreadNotificationCount', 200>;
export type MarkNotificationReadResponse = OperationResponseByStatus<'markNotificationRead', 200>;
export type MarkAllNotificationsReadResponse = OperationResponseByStatus<'markAllNotificationsRead', 200>;

export type NotificationSchema = Schema<'Notification'>;
