import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type CreateReviewRequest = OperationRequest<'createReview'>;
export type CreateReviewResponse = OperationResponseByStatus<'createReview', 201>;

export type ListCompanyReviewsResponse = OperationResponseByStatus<'listCompanyReviews', 200>;
export type ListServiceReviewsResponse = OperationResponseByStatus<'listServiceReviews', 200>;
export type ListSpecialistReviewsResponse = OperationResponseByStatus<'listSpecialistReviews', 200>;

export type ReviewSchema = Schema<'Review'>;
