import { z } from 'zod';

import type { SendSpecialistRequestRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const sendSpecialistRequestSchema: z.ZodType<SendSpecialistRequestRequest> = z.object({
  specialistProfileId: z.string().uuid(),
  message: z.string().nullable().optional(),
});

export type SendSpecialistRequestInput = z.infer<typeof sendSpecialistRequestSchema>;

export const requestIdParamsSchema = z.object({
  requestId: z.string().uuid(),
});

export type RequestIdParams = z.infer<typeof requestIdParamsSchema>;
