import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type CreateServiceRequest = OperationRequest<'createService'>;
export type CreateServiceResponse = OperationResponseByStatus<'createService', 201>;

export type UpdateServiceRequest = OperationRequest<'updateService'>;
export type UpdateServiceResponse = OperationResponseByStatus<'updateService', 200>;

export type ListCompanyServicesResponse = OperationResponseByStatus<'listCompanyServices', 200>;
export type ListPublicServicesResponse = OperationResponseByStatus<'listPublicServices', 200>;
export type GetServiceByIdResponse = OperationResponseByStatus<'getServiceById', 200>;

export type ServiceSchema = Schema<'Service'>;
