import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type SendSpecialistRequestRequest = OperationRequest<'sendSpecialistRequest'>;
export type SendSpecialistRequestResponse = OperationResponseByStatus<'sendSpecialistRequest', 201>;

export type ListCompanySpecialistRequestsResponse = OperationResponseByStatus<'listCompanySpecialistRequests', 200>;
export type ListCompanySpecialistsResponse = OperationResponseByStatus<'listCompanySpecialists', 200>;
export type ListMySpecialistCompanyRequestsResponse = OperationResponseByStatus<'listMySpecialistCompanyRequests', 200>;
export type ListMySpecialistCompaniesResponse = OperationResponseByStatus<'listMySpecialistCompanies', 200>;

export type AcceptSpecialistCompanyRequestResponse = OperationResponseByStatus<'acceptSpecialistCompanyRequest', 200>;
export type RejectSpecialistCompanyRequestResponse = OperationResponseByStatus<'rejectSpecialistCompanyRequest', 200>;

export type CompanySpecialistRequestSchema = Schema<'CompanySpecialistRequest'>;
export type CompanySpecialistSchema = Schema<'CompanySpecialist'>;
