import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type CreateCompanyRequest = OperationRequest<'createCompany'>;
export type CreateCompanyResponse = OperationResponseByStatus<'createCompany', 201>;

export type GetPublicCompaniesResponse = OperationResponseByStatus<'getPublicCompanies', 200>;

export type GetMyCompaniesResponse = OperationResponseByStatus<'getMyCompanies', 200>;

export type GetCompanyByIdResponse = OperationResponseByStatus<'getCompanyById', 200>;
export type GetCompanyByIdNotFound = OperationResponseByStatus<'getCompanyById', 404>;

export type UpdateCompanyRequest = OperationRequest<'updateCompany'>;
export type UpdateCompanyResponse = OperationResponseByStatus<'updateCompany', 200>;

export type CompanySchema = Schema<'Company'>;
export type CompanyMembershipSchema = Schema<'CompanyMembership'>;
