import type { OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type GetAppDashboardSummaryResponse = OperationResponseByStatus<'getAppDashboardSummary', 200>;
export type GetCompanyDashboardSummaryResponse = OperationResponseByStatus<'getCompanyDashboardSummary', 200>;

export type AppDashboardSummarySchema = Schema<'AppDashboardSummary'>;
export type CompanyDashboardSummarySchema = Schema<'CompanyDashboardSummary'>;
