import type { AppDashboardSummarySchema, CompanyDashboardSummarySchema } from '@/autogenerated/types/index.js';
import { AppError } from '@/common/errors/AppError.js';
import { requireCompanyRole } from '@/common/permissions/companyPermissions.js';
import { AppDataSource } from '@/infrastructure/database/data-source.js';
import { Appointment, AppointmentStatus } from '@/modules/appointments/appointment.entity.js';
import { CompanyMember, CompanyMemberRole, CompanyMemberStatus } from '@/modules/company-members/company-member.entity.js';
import {
  CompanySpecialistRequest,
  CompanySpecialistRequestStatus,
} from '@/modules/company-specialists/company-specialist-request.entity.js';
import { CompanySpecialist, CompanySpecialistStatus } from '@/modules/company-specialists/company-specialist.entity.js';
import { Company } from '@/modules/companies/company.entity.js';
import { countUnreadNotifications } from '@/modules/notifications/notifications.service.js';
import { ServiceSpecialist } from '@/modules/services/service-specialist.entity.js';
import { Service, ServiceStatus } from '@/modules/services/service.entity.js';
import { SpecialistProfile } from '@/modules/specialists/specialist-profile.entity.js';

export async function getAppDashboardSummary(userId: string): Promise<AppDashboardSummarySchema> {
  const appointmentRepository = AppDataSource.getRepository(Appointment);
  const membershipRepository = AppDataSource.getRepository(CompanyMember);
  const specialistRepository = AppDataSource.getRepository(SpecialistProfile);

  const [unreadNotifications, memberships, specialist, pending, approved, completed] = await Promise.all([
    countUnreadNotifications(userId),
    membershipRepository.find({
      where: { userId, status: CompanyMemberStatus.ACTIVE },
      relations: { company: true },
      order: { createdAt: 'DESC' },
    }),
    specialistRepository.findOne({ where: { userId } }),
    appointmentRepository.count({ where: { clientUserId: userId, status: AppointmentStatus.PENDING } }),
    appointmentRepository.count({ where: { clientUserId: userId, status: AppointmentStatus.APPROVED } }),
    appointmentRepository.count({ where: { clientUserId: userId, status: AppointmentStatus.COMPLETED } }),
  ]);

  const specialistSummary = specialist
    ? await buildSpecialistSummary(specialist)
    : null;

  const roles: AppDashboardSummarySchema['roles'] = ['client'];
  if (memberships.length > 0) roles.push('company');
  if (specialist) roles.push('specialist');

  return {
    roles,
    unreadNotifications,
    appointments: { pending, approved, completed },
    companies: memberships.map(({ company, role }) => ({
      id: company.id,
      name: company.name,
      status: company.status,
      role,
    })),
    specialist: specialistSummary,
  };
}

async function buildSpecialistSummary(
  specialist: SpecialistProfile,
): Promise<NonNullable<AppDashboardSummarySchema['specialist']>> {
  const [pendingCompanyRequests, activeCompanies, assignedServices] = await Promise.all([
    AppDataSource.getRepository(CompanySpecialistRequest).count({
      where: {
        specialistProfileId: specialist.id,
        status: CompanySpecialistRequestStatus.PENDING,
      },
    }),
    AppDataSource.getRepository(CompanySpecialist).count({
      where: {
        specialistProfileId: specialist.id,
        status: CompanySpecialistStatus.ACTIVE,
      },
    }),
    AppDataSource.getRepository(ServiceSpecialist).count({
      where: { specialistProfileId: specialist.id },
    }),
  ]);

  return {
    id: specialist.id,
    status: specialist.status,
    pendingCompanyRequests,
    activeCompanies,
    assignedServices,
  };
}

export async function getCompanyDashboardSummary(
  companyId: string,
  userId: string,
): Promise<CompanyDashboardSummarySchema> {
  const membership = await requireCompanyRole(companyId, userId, [
    CompanyMemberRole.OWNER,
    CompanyMemberRole.MANAGER,
  ]);

  const [
    company,
    pendingAppointments,
    activeSpecialists,
    pendingSpecialistRequests,
    activeMembers,
    totalServices,
    draftServices,
    publishedServices,
  ] = await Promise.all([
    AppDataSource.getRepository(Company).findOne({ where: { id: companyId } }),
    AppDataSource.getRepository(Appointment).count({
      where: { companyId, status: AppointmentStatus.PENDING },
    }),
    AppDataSource.getRepository(CompanySpecialist).count({
      where: { companyId, status: CompanySpecialistStatus.ACTIVE },
    }),
    AppDataSource.getRepository(CompanySpecialistRequest).count({
      where: { companyId, status: CompanySpecialistRequestStatus.PENDING },
    }),
    AppDataSource.getRepository(CompanyMember).count({
      where: { companyId, status: CompanyMemberStatus.ACTIVE },
    }),
    AppDataSource.getRepository(Service).count({ where: { companyId } }),
    AppDataSource.getRepository(Service).count({
      where: { companyId, status: ServiceStatus.DRAFT },
    }),
    AppDataSource.getRepository(Service).count({
      where: { companyId, status: ServiceStatus.PUBLISHED },
    }),
  ]);

  if (!company) {
    throw new AppError('Company not found', 404);
  }

  return {
    company: {
      ...company,
      createdAt: company.createdAt.toISOString(),
      updatedAt: company.updatedAt.toISOString(),
    },
    role: membership.role,
    pendingAppointments,
    activeSpecialists,
    pendingSpecialistRequests,
    activeMembers,
    services: {
      total: totalServices,
      draft: draftServices,
      published: publishedServices,
    },
  };
}
