import type { OperationRequest, OperationResponseByStatus, Schema } from '@/autogenerated/types/core.js';

export type ListCompanyMembersResponse = OperationResponseByStatus<'listCompanyMembers', 200>;

export type InviteCompanyMemberRequest = OperationRequest<'inviteCompanyMember'>;
export type InviteCompanyMemberResponse = OperationResponseByStatus<'inviteCompanyMember', 201>;

export type UpdateCompanyMemberRequest = OperationRequest<'updateCompanyMember'>;
export type UpdateCompanyMemberResponse = OperationResponseByStatus<'updateCompanyMember', 200>;

export type RemoveCompanyMemberResponse = OperationResponseByStatus<'removeCompanyMember', 200>;

export type CompanyMemberSchema = Schema<'CompanyMember'>;
