import { z } from 'zod';

import type { InviteCompanyMemberRequest, UpdateCompanyMemberRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const inviteMemberRequestSchema: z.ZodType<InviteCompanyMemberRequest> = z.object({
  email: z.string().email(),
});

export type InviteMemberRequestInput = z.infer<typeof inviteMemberRequestSchema>;

export const updateMemberRequestSchema: z.ZodType<UpdateCompanyMemberRequest> = z.object({
  status: z.enum(['active', 'removed']),
});

export type UpdateMemberRequestInput = z.infer<typeof updateMemberRequestSchema>;

export const memberIdParamsSchema = z.object({
  companyId: z.string().uuid(),
  memberId: z.string().uuid(),
});

export type MemberIdParams = z.infer<typeof memberIdParamsSchema>;
