import { z } from 'zod';

import type {
  CreateSpecialistProfileRequest,
  GetPublicSpecialistsQuery,
  UpdateSpecialistProfileRequest,
} from '@/autogenerated/types/index.js';
import { paginationQuerySchema } from '@/common/schemas/pagination.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const createSpecialistProfileRequestSchema: z.ZodType<CreateSpecialistProfileRequest> = z.object({
  displayName: z.string().min(1),
  headline: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  isRemoteSupported: z.boolean().optional(),
});

export type CreateSpecialistProfileRequestInput = z.infer<typeof createSpecialistProfileRequestSchema>;

export const updateSpecialistProfileRequestSchema: z.ZodType<UpdateSpecialistProfileRequest> = z.object({
  displayName: z.string().min(1).optional(),
  headline: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  isRemoteSupported: z.boolean().optional(),
  // `suspended` is a moderation state, not settable by the profile owner via this endpoint.
  status: z.enum(['draft', 'published']).optional(),
});

export type UpdateSpecialistProfileRequestInput = z.infer<typeof updateSpecialistProfileRequestSchema>;

export const specialistIdParamsSchema = z.object({
  specialistId: z.string().uuid(),
});

export type SpecialistIdParams = z.infer<typeof specialistIdParamsSchema>;

export const publicSpecialistsQuerySchema: z.ZodType<GetPublicSpecialistsQuery> = paginationQuerySchema.extend({
  q: z.string().trim().min(1).optional(),
  category: z.string().trim().min(1).optional(),
  city: z.string().trim().min(1).optional(),
  // Query params always arrive as strings - accept "true"/"false" and coerce to boolean.
  remoteOnly: z
    .union([z.literal('true'), z.literal('false')])
    .optional()
    .transform((value) => (value === undefined ? undefined : value === 'true')),
});

export type PublicSpecialistsQueryInput = z.infer<typeof publicSpecialistsQuerySchema>;
