import { z } from 'zod';

import type { CreateSpecialistProfileRequest, UpdateSpecialistProfileRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const createSpecialistProfileRequestSchema: z.ZodType<CreateSpecialistProfileRequest> = z.object({
  displayName: z.string().min(1),
  headline: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  isRemoteSupported: z.boolean().optional(),
});

export type CreateSpecialistProfileRequestInput = z.infer<typeof createSpecialistProfileRequestSchema>;

export const updateSpecialistProfileRequestSchema: z.ZodType<UpdateSpecialistProfileRequest> = z.object({
  displayName: z.string().min(1).optional(),
  headline: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  isRemoteSupported: z.boolean().optional(),
  // `suspended` is a moderation state, not settable by the profile owner via this endpoint.
  status: z.enum(['draft', 'published']).optional(),
});

export type UpdateSpecialistProfileRequestInput = z.infer<typeof updateSpecialistProfileRequestSchema>;

export const specialistIdParamsSchema = z.object({
  specialistId: z.string().uuid(),
});

export type SpecialistIdParams = z.infer<typeof specialistIdParamsSchema>;
