import { z } from 'zod';

import type { AssignServiceSpecialistRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const assignServiceSpecialistRequestSchema: z.ZodType<AssignServiceSpecialistRequest> = z.object({
  specialistProfileId: z.string().uuid(),
});

export type AssignServiceSpecialistInput = z.infer<typeof assignServiceSpecialistRequestSchema>;

export const serviceSpecialistParamsSchema = z.object({
  serviceId: z.string().uuid(),
  specialistProfileId: z.string().uuid(),
});

export type ServiceSpecialistParams = z.infer<typeof serviceSpecialistParamsSchema>;
