import { z } from 'zod';

import type { CreateServiceRequest, UpdateServiceRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const createServiceRequestSchema: z.ZodType<CreateServiceRequest> = z.object({
  name: z.string().min(1),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  durationMinutes: z.number().int().min(1),
  price: z.string().nullable().optional(),
});

export type CreateServiceRequestInput = z.infer<typeof createServiceRequestSchema>;

export const updateServiceRequestSchema: z.ZodType<UpdateServiceRequest> = z.object({
  name: z.string().min(1).optional(),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  durationMinutes: z.number().int().min(1).optional(),
  price: z.string().nullable().optional(),
  // `suspended` is a moderation state, not settable by the owner/manager via this endpoint.
  status: z.enum(['draft', 'published']).optional(),
});

export type UpdateServiceRequestInput = z.infer<typeof updateServiceRequestSchema>;

export const serviceIdParamsSchema = z.object({
  companyId: z.string().uuid(),
  serviceId: z.string().uuid(),
});

export type ServiceIdParams = z.infer<typeof serviceIdParamsSchema>;

export const serviceOnlyIdParamsSchema = z.object({
  serviceId: z.string().uuid(),
});

export type ServiceOnlyIdParams = z.infer<typeof serviceOnlyIdParamsSchema>;
