import { z } from 'zod';

import type { CreateUserRequest, UpdateUserRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// `CreateUserRequest` type so it stays structurally in sync with contracts/openapi.yaml;
// if it drifts, TypeScript errors here rather than at runtime.
export const createUserRequestSchema: z.ZodType<CreateUserRequest> = z.object({
  email: z.string().email(),
  name: z.string().min(1),
});

export const userIdParamsSchema = z.object({
  id: z.string().uuid(),
});

export type UserIdParams = z.infer<typeof userIdParamsSchema>;

export const updateUserRequestSchema: z.ZodType<UpdateUserRequest> = z.object({
  name: z.string().min(1).optional(),
  phone: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
});

export type UpdateUserRequestInput = z.infer<typeof updateUserRequestSchema>;
