import { z } from 'zod';

import type { CreateCompanyRequest, UpdateCompanyRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const createCompanyRequestSchema: z.ZodType<CreateCompanyRequest> = z.object({
  name: z.string().min(1),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  website: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  isRemoteSupported: z.boolean().optional(),
  city: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
});

export type CreateCompanyRequestInput = z.infer<typeof createCompanyRequestSchema>;

export const updateCompanyRequestSchema: z.ZodType<UpdateCompanyRequest> = z.object({
  name: z.string().min(1).optional(),
  description: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  website: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  isRemoteSupported: z.boolean().optional(),
  city: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
  // `suspended` is a moderation state, not settable by the owner/manager via this endpoint.
  status: z.enum(['draft', 'published']).optional(),
});

export type UpdateCompanyRequestInput = z.infer<typeof updateCompanyRequestSchema>;

export const companyIdParamsSchema = z.object({
  companyId: z.string().uuid(),
});

export type CompanyIdParams = z.infer<typeof companyIdParamsSchema>;
