#!/usr/bin/env sh

branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo "HEAD")

if [ "$branch" = "main" ]; then
  exit 0
fi

commit_msg_file="$1"
commit_msg=$(head -n1 "$commit_msg_file")
pattern='^[0-9]+\.[0-9]{2}: .+$'

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo ""
  echo "Invalid commit message: '$commit_msg'"
  echo "Expected: <ticket>: <description>, e.g. 1.01: add fsd import boundaries"
  echo ""
  exit 1
fi
