import { z } from 'zod';

import type { CreateReviewRequest } from '@/autogenerated/types/index.js';

export const createReviewRequestSchema: z.ZodType<CreateReviewRequest> = z.object({
  rating: z.number().int().min(1).max(5),
  comment: z.string().nullable().optional(),
});

export type CreateReviewInput = z.infer<typeof createReviewRequestSchema>;
