import { z } from 'zod';

import type { CreateAppointmentRequest, RespondToAppointmentRequest } from '@/autogenerated/types/index.js';

// Plain, classic Zod - no OpenAPI library involved. Typed against the generated
// request types so it stays structurally in sync with contracts/openapi.yaml; if it
// drifts, TypeScript errors here rather than at runtime.
export const createAppointmentRequestSchema: z.ZodType<CreateAppointmentRequest> = z.object({
  serviceId: z.string().uuid(),
  specialistProfileId: z.string().uuid().nullable().optional(),
  requestedStartAt: z.string().datetime(),
  notes: z.string().nullable().optional(),
});

export type CreateAppointmentInput = z.infer<typeof createAppointmentRequestSchema>;

export const respondToAppointmentRequestSchema: z.ZodType<RespondToAppointmentRequest> = z.object({
  status: z.enum(['approved', 'rejected']),
});

export type RespondToAppointmentInput = z.infer<typeof respondToAppointmentRequestSchema>;

export const appointmentIdParamsSchema = z.object({
  companyId: z.string().uuid(),
  appointmentId: z.string().uuid(),
});

export type AppointmentIdParams = z.infer<typeof appointmentIdParamsSchema>;

export const appointmentOnlyIdParamsSchema = z.object({
  appointmentId: z.string().uuid(),
});

export type AppointmentOnlyIdParams = z.infer<typeof appointmentOnlyIdParamsSchema>;
